# Default configuration parameters
# This file serves as the base configuration that other YAML files can override

# Trial and evidence settings
default_trial: "snack1"
default_evidence: "visual"

# Sampling configuration
sampling:
  max_steps: 25                    # Maximum steps per path
  num_suspect_paths: 50           # Number of suspect paths to sample
  num_detective_paths: 1000       # Number of detective predictions to sample
  seed: 42                        # Random seed for sampling
  naive_temp: 0.1                 # Temperature for naive agent sampling
  sophisticated_temp: 0.1         # Temperature for sophisticated agent sampling
  cost_weight: 1.0                # Weight for path cost in utility function

# Evidence configuration
evidence:
  evidence_type: "visual"                           # Type of evidence: visual, audio, multimodal
  naive_detective_sigma: 1.0                       # Noise parameter for naive detective predictions
  crumb_planting_sigma: 1.0                        # Uncertainty in evidence planting
  sophisticated_detective_sigma: 1.0               # Noise parameter for sophisticated detective predictions
  visual_naive_likelihood_alpha: 0.01              # Visual evidence strength for naive agents
  visual_sophisticated_likelihood_alpha: 1.0       # Visual evidence strength for sophisticated agents
  
  # Audio evidence settings (used when evidence_type is audio or multimodal)
  audio_similarity_sigma: 0.3                      # Audio similarity noise parameter
  audio_gt_step_size: 2                           # Audio ground truth step size

# Simulation settings
simulation:
  log_dir: "results"                        # Directory for simulation results
  log_dir_base: "results"                   # Base directory for all logging
  save_intermediate_results: true                 # Whether to save intermediate results
