# Default config parameters

# Sampling
sampling:
  max_steps: 25
  num_suspect_paths: 50
  num_detective_paths: 1000
  seed: 42
  naive_temp: 0.1
  sophisticated_temp: 0.1
  cost_weight: 0.3

# Evidence
evidence:
  naive_detective_sigma: 0.5 
  crumb_planting_sigma: 1.0 
  sophisticated_detective_sigma: 2.0
  
  # Audio
  audio_similarity_sigma: 0.3
  audio_gt_step_size: 2

# Simulation
simulation:
  log_dir: "../../results"

# TODO: move to under simulation?
default_trial: "snack1"
default_evidence: "visual"
